name: INT Outbound Calls
on:
  workflow_dispatch:
jobs:
  build:
    name: IntOutboundCalls
    runs-on: ubuntu-latest
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@int
       with:
          egress-policy: audit
     - run: "curl https://google.com -L  || true"
     - run: "curl microsoft.com:443  --connect-timeout 5 || true"
     - run: "curl amazon.com:443  --connect-timeout 5 || true"     
